# Dynamic wallpaper color scheme for Kitty

# Basic colors
foreground            #e4e1e9
background            #131318
selection_foreground  #e0e0ff
selection_background  #3e4278

# Cursor colors
cursor            #bfc2ff
cursor_text_color #272b60

# URL underline color when hovering with mouse
url_color #e8b9d5

# Kitty window border colors
active_border_color   #bfc2ff
inactive_border_color #1f1f25
bell_border_color     #ffb4ab

# Tab bar colors
active_tab_foreground   #272b60
active_tab_background   #bfc2ff
inactive_tab_foreground #c7c5d0
inactive_tab_background #1f1f25
tab_bar_background      #131318

# Terminal colors (16 ANSI colors)

# black
color0 #1b1b21
color8 #35343a

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2 #c5c4dd
color10 #c5c4dd

# yellow
color3 #3e4278
color11 #3e4278

# blue
color4 #bfc2ff
color12 #bfc2ff

# magenta
color5 #444559
color13 #444559

# cyan
color6 #e8b9d5
color14 #e8b9d5

# white
color7 #c7c5d0
color15 #e4e1e9
